env: "${ENV}" # This will be replaced by the ENV variable

log:
  log_level: "${LOG_LEVEL}"
  #    - "INFO", "WARN", "ERROR", "DEBUG" - and environment specific log level


cache:
  enabled: true
  default_cache_timeout: 15


auth:
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://localhost:9001"

addr:
  host: 127.0.0.1
  port: 8900

auth_server:
  introspectionEndpoint: "https://localhost:9443/oauth2/introspect"
  tokenEndpoint: "https://localhost:9443/oauth2/token"
  revocationEndpoint: "https://localhost:9443/oauth2/revoke"
  client_id: "zWnggcx_LNj9MSuZYxXyyo5lcaIa"
  client_secret: "${AUTH_SERVER_CLIENT_SECRET}"
  admin_username: "admin"
  admin_password: "${AUTH_SERVER_ADMIN_PASSWORD}"
  required_scopes:
    profile:view:
      - "internal_cds_profile_view"
    profile:delete:
      - "internal_cds_profile_delete"

    unification_rules:view:
      - "internal_cds_unification_view"
    unification_rules:create:
      - "internal_cds_unification_create"
    unification_rules:update:
      - "internal_cds_unification_update"
    unification_rules:delete:
      - "internal_cds_unification_delete"

    enrichment_rules:view:
      - "internal_cds_enrichment_rule_view"
    enrichment_rules:create:
      - "internal_cds_enrichment_rule_create"
    enrichment_rules:update:
      - "internal_cds_enrichment_rule_update"
    enrichment_rules:delete:
      - "internal_cds_enrichment_rule_delete"

    events:view:
      - "internal_cds_event_view"


database:
  host: "localhost"
  port: "5432"
  user: "cdsuser"
  password: "cdspwd"
  dbname: "cdsdb"

datasource:
  hostname: "localhost"
  port: 5432
  username: "cdsuser"
  password: "cdspwd"
  name: "cdsdb"
  sslmode: disable
