name: PR Builder

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]
    branches:
      - poc-cds

jobs:
  build-and-lint:
    if: github.event_name == 'pull_request' && 
        (github.event.action == 'synchronize' || contains(github.event.pull_request.labels.*.name, 'trigger-pr-builder'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install system deps
        run: sudo apt-get install -y make zip

      - name: Build
        run: make build

      - name: Lint
        run: make lint
        
      - name: Run Integration Tests
        run: make integration-test
